name: Update Release Tags

on:
  release:
    types: [ published ]

jobs:
  update-tags:
    if: ${{ !github.event.release.prerelease }}
    name: Update Running Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sersoft-gmbh/running-release-tags-action@v3
        with:
          update-full-release: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
